title: 4bitcss
description: >- 
  4bitcss: CSS3 16-color schemes.
permalink: pretty
analyticsID: G-27ME7M0HYR
defaults:
  - values:
      layout: "default"
baseurl: ""

collections:
  my_collection:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
